/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kwon37xi' at '16. 5. 12 오후 10:40' with Gradle 2.12
 *
 * @author kwon37xi, @date 16. 5. 12 오후 10:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
